title: 'BitDevsYDE'
tagline: 'BitDevsYDE is a monthly meetup devoted to the research and development of Bitcoin'

menu:
  - {name: 'X', url: 'https://x.com/BitDevsYDE', external: true}
  - {name: 'Discord', url: 'https://discord.gg/RQmYSGJeNZ', external: true}
  - {name: 'Luma', url: 'https://lu.ma/bitdevsyde', external: true}
